# Generated by Django 5.2.7 on 2025-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_grouppermission_usergroup'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupPermission',
            new_name='Group_Permissions',
        ),
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='User_Groups',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
